name: Create Release Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Archive
        run: |
          # Создаем целевую директорию
          mkdir ItemStorageBrowser
          
          # Копируем ВСЁ, кроме скрытых папок (.git, .github) и самого архива
          # --exclude исключает ненужное
          # . ItemStorageBrowser/ копирует всё из текущего места в папку аддона
          rsync -av . ItemStorageBrowser/ --exclude '.git*' --exclude 'ItemStorageBrowser' --exclude 'ItemStorageBrowser.zip'
          
          # Упаковываем в ZIP
          zip -r ItemStorageBrowser.zip ItemStorageBrowser

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ItemStorageBrowser.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}